"""initial

Revision ID: 4be0c0ab5c33
Revises: 926b92d6a434
Create Date: 2025-06-26 14:09:45.742209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be0c0ab5c33'
down_revision = '926b92d6a434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
