"""initial

Revision ID: 926b92d6a434
Revises: 45d3eb02ccef
Create Date: 2025-06-26 14:05:49.645531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926b92d6a434'
down_revision = '45d3eb02ccef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
