"""initial

Revision ID: b25656c1bc94
Revises: 4be0c0ab5c33
Create Date: 2025-06-26 15:25:35.356667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25656c1bc94'
down_revision = '4be0c0ab5c33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
